version: "2.6.0"
services:
  client:
    container_name: client
    image: ciatphdev/firebase-users-admin-client:latest
    env_file:
      - ./client/.env
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"

  server:
    container_name: server
    image: ciatphdev/firebase-users-admin-server:latest
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    ports:
      - "3001:3001"
