name: Push To Docker Hub

on:
  push:
    branches:
      - 'docker-hub'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Build Images
        run: docker-compose -f docker-compose.prod.yml build
      - name: Push Images to Docker Hub
        run: docker-compose -f docker-compose.prod.yml push
